### ISSUE TITLE
Add in your Hello, World code!

### ISSUE THREAD

**Issue by ktgibson** [ktgibson/HelloWorldDirectory#6]
## Read the README!
Create a pull request and add in your favorite Hello, World code! Can be as simple or as complex as you like. The more obscure and complex the better! Can't wait to see what you guys add.

**Comment by afflato** [comment]
Hey Can I add one in typescript?

**Comment by ktgibson** [comment]
> Hey Can I add one in typescript?

Sorry for the late reply. I noticed you already contributed though so thank you! I merged that PR this morning.

**Comment by ktgibson** [comment]
Fin!
